### ISSUE TITLE
Add lookAt?

### ISSUE THREAD

**Issue by Ohmnivore** [FuzzyWuzzie/haxe-glm#4]
Very useful in my opinion

**Comment by hamaluik** [comment]
For sure! There are a bunch of things like this, I just haven't had the time yet. In the meantime, feel free to submit a pull request!

**Comment by m-sifi** [comment]
#8 I made a pull request implementing this method
![ss 2016-02-20 at 04 13 11](https://cloud.githubusercontent.com/assets/2879199/13195422/e878a868-d7ec-11e5-86d0-62813d0dda07.png)

**Comment by hamaluik** [comment]
Still todo: some documentation on the function, and update the release.
